---
title: "\\textbf{Práctica 3 - Intervalos de Confianza}"
author: "\\textbf{Rodrigo Quirno Costa}"
date: "\\textbf{03/05/2026}"
output: 
  pdf_document:
    latex_engine: xelatex
header-includes:
  - \usepackage{xcolor}
  - \usepackage{framed}
  - \definecolor{shadecolor}{RGB}{232, 238, 246}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo    = TRUE,
	message = FALSE,
	warning = FALSE,
	comment = ""
)
library(knitr)
```

# 11. Intervalo para $\mathcal{B}(1, p)$

i. Metodo 1: ($\sigma^2 = \bar{X}(1-\bar{X})$) 
```{r results='asis'}
rm(list = ls()) # limpiar env
set.seed(42)
ns    <- c(20, 50, 100)
ps    <- c(0.1, 0.5)
k     <- 2000
nivel <- 0.95

# caluclar intervalo de confianza asintotico
intervalo_1  <- function(datos, n, nivel){
  sigma <- sqrt(mean(datos) * (1 - mean(datos))) 
  a     <- mean(datos) - qnorm((1 + nivel)/2) * (sigma/sqrt(n))
  b     <- mean(datos) + qnorm((1 + nivel)/2) * (sigma/sqrt(n))
  c(a,b)
}

for (n in ns) {
  for (p in ps){
    res <- replicate(k, {
      d   <- rbinom(n, 1, p)
      ic  <- intervalo_1(d, n, nivel)
      c(
        ic[2] - ic[1],             #longitud
        (p >= ic[1] & p <= ic[2])  #cubrimiento
      )    
    })
    rm <- rowMeans(res)
    cat("Para $n =$", n, "y $p =$", p, ":\n\n",
        "a) $\\widehat{\\mathbb{E}}[L_1] =$", rm[1], "\n\n",
        "b) $\\widehat{Cob}_1 =$", rm[2], "\n\n")
  }
}
```

ii. Metodo 2: hallar $[\widehat{p}_{1,n},\widehat{p}_{2,n}]$ raíces del plinomio en $p$:\\
Partimos de elevar al cuadrado toda la desigualdad (lo que equivale a pedir que el valor absoluto sea $\le z_{a/2}$):
$$
\frac{(\bar{X} - p)^2}{\frac{p(1-p)}{n}} \leq z_{a/2}^2
$$
$$
n(\bar{X} - p)^2 \leq z_{a/2}^2 \cdot p(1 - p)
$$
$$
n\bar{X}^2 - 2n\bar{X}p + np^2 \leq z_{a/2}^2 p - z_{a/2}^2 p^2
$$
$$
n\bar{X}^2 - 2n\bar{X}p + np^2 - z_{a/2}^2 p + z_{a/2}^2 p^2 \leq 0
$$
Agrupamos por potencias de $p$:
$$
\underbrace{n\bar{X}^2}_{\text{cte}} - \underbrace{p(2n\bar{X} + z_{a/2}^2)}_{p^1} + \underbrace{p^2(n + z_{a/2}^2)}_{p^2} \leq 0
$$
```{r results='asis'}
set.seed(42)

# caluclar intervalo de confianza asintotico
intervalo_2 <- function(datos, n, nivel){
  z  <- qnorm((1 + nivel) / 2)
  X  <- mean(datos)
  
  a <-  n + z^2
  b <- -(2*n*X + z^2)
  c <-  n*X^2
  
  #cuadratica
  disc <- b^2 - 4*a*c
  p1   <- (-b - sqrt(disc)) / (2*a)
  p2   <- (-b + sqrt(disc)) / (2*a)
  
  c(p1, p2)
}

for (n in ns) {
  for (p in ps){
    res <- replicate(k, {
      d   <- rbinom(n, 1, p)
      ic  <- intervalo_2(d, n, nivel)
      c(
        ic[2] - ic[1],             
        (p >= ic[1] & p <= ic[2])  
      )    
    })
    rm <- rowMeans(res)
    cat("Para $n =$", n, "y $p =$", p, ":\n\n",
        "a) $\\widehat{\\mathbb{E}}[L_2] =$", rm[1], "\n\n",
        "b) $\\widehat{Cob}_2 =$", rm[2], "\n\n")
  }
}
```

---
